"""empty message

Revision ID: 334a0098047f
Revises: ab9f4b422879
Create Date: 2016-08-29 03:20:54.648000

"""

# revision identifiers, used by Alembic.
revision = '334a0098047f'
down_revision = 'ab9f4b422879'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
