"""empty message

Revision ID: 8df56cccad22
Revises: None
Create Date: 2016-08-29 01:33:58.596000

"""

# revision identifiers, used by Alembic.
revision = '8df56cccad22'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'description')
    ### end Alembic commands ###
