"""empty message

Revision ID: c607f590cca8
Revises: 334a0098047f
Create Date: 2016-08-29 12:06:08.235000

"""

# revision identifiers, used by Alembic.
revision = 'c607f590cca8'
down_revision = '334a0098047f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
